creates a conveniently named junk directory. working.

diff --git a/bin/junkdir b/bin/junkdir
--- a/bin/junkdir
+++ b/bin/junkdir
@@ -1,6 +1,9 @@
 #!/bin/sh
 # junkdir -- creates a convenient junk directory under $HOME
-cd $HOME
+
+# clean up empties
+rmdir $HOME/junk* 2>/dev/null
+
 for i in 1 2 3 4 5 6 7 8 9; do
 	j=$HOME/junk$i$i
 	if test -d $j; then
@@ -11,3 +14,4 @@ for i in 1 2 3 4 5 6 7 8 9; do
 		exit 0
 	fi
 done
+exit 1
